### ISSUE TITLE
REQ: Block Creativity Inspiration Letter

### ISSUE THREAD

**Issue by DanPli** [MrChimick/BlockUnwantedMinutiae#1]
Please add the functionality to block the "has experienced a creativity inspiration" blue alert.

Thank you :)

**Comment by MrChimick** [comment]
It's actually a letter (the boxes that come up are referred to as letters) but it was easy to pull together it's letters and some connected messages, so those have been added.
9ba565d4feb4164127d15c6bceeb3ac9e4bcb386
