### ISSUE TITLE
Could we get support for Empire mod alerts and letters

### ISSUE THREAD

**Issue by Draculazla** [MrChimick/BlockUnwantedMinutiae#2]
Empire mod floods letters and alerts atleast after you start going to +10 colonies.

**Comment by MrChimick** [comment]
I'm still considering whether I plan to add support for other mods, but can you post a couple examples of the alerts and letters that come up most frequently?

**Comment by Draculazla** [comment]
"Taxes from x (settlement name) have been delivered!
Silver (reward) 111 (amount)

**Comment by Draculazla** [comment]
Any plans for mod support yet?

**Comment by MrChimick** [comment]
Given the scale of the mod just from the vanilla expansions, I don't think I'll ever bother to add different mod messages.
