### ISSUE TITLE
Could a way to disable health condition letters be added?

### ISSUE THREAD

**Issue by SariusSkelrets** [MrChimick/BlockUnwantedMinutiae#7]
After getting a lot of catatonic breakdown notifications (I disabled the breakdowns themselves so they're not a problem), I tried to use your mod to disable said notifications but couldn't find a suitable option

Could a way to disable the letters on pawns getting conditions (or better, a way to disable the catatonic breakdown nootification alone) be added to your mod?
![breaks](https://user-images.githubusercontent.com/68650913/168440946-a6828380-1838-4cc8-a25d-736c179464a5.png)

**Comment by MrChimick** [comment]
I'm adding these as part of the 1.4 update.
