### ISSUE TITLE
Feature Request: Tickbox for individual colonists to ignore idle status

### ISSUE THREAD

**Issue by AsheIsAmazing** [MrChimick/BlockUnwantedMinutiae#8]
As in the title, it would be really cool to me if there was a tickbox on your colonists somewhere that allows you to ignore idle status for that colonist, much like how you do with guests, so no alert is prompted from their idleness.
Helps for colonists that have most of their work types disabled from an ideology role, or someone who is nigh-useless for work but you're keeping around for other reasons etc, since it's expected that they will go idle and that is an acceptable outcome, but that you still want idle alerts active for everyone else.

**Comment by MrChimick** [comment]
I'd put adding extra buttons to the UI like this firmly outside the scope of functionality I'd like for this mod, but you can currently disable the idle alerts for all your colonists if it annoys you.
